plugins {
    id 'java-library'
    id 'maven-publish'
    id("com.gradleup.shadow") version "9.3.1" apply false
}

ext {
    group = "fr.ibrakash.helper"
    version = "2.0.0-SNAPSHOT"

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    apply plugin: "java-library"
    apply plugin: "com.gradleup.shadow"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
        withJavadocJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release = 21
    }

    dependencies {
        // Databases Libraries
        compileOnly 'org.mariadb.jdbc:mariadb-java-client:3.3.3'
        compileOnly 'mysql:mysql-connector-java:8.0.29'
        compileOnly 'org.postgresql:postgresql:42.7.4'
        compileOnly 'org.xerial:sqlite-jdbc:3.46.0.1'
        compileOnly 'com.zaxxer:HikariCP:5.0.1'
        compileOnly 'org.jdbi:jdbi3-core:3.49.6'
        compileOnly 'org.mongodb:mongodb-driver-sync:5.3.1'

        // Configuration Libraries
        compileOnly 'org.spongepowered:configurate-core:4.2.0'
        compileOnly 'org.spongepowered:configurate-yaml:4.2.0'
        compileOnly 'org.spongepowered:configurate-hocon:4.2.0'
        compileOnly 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.20.0'
    }

    tasks.test {
        useJUnitPlatform()
    }

    tasks.jar {
        archiveClassifier.set("plain")
    }

    tasks.shadowJar {
        archiveClassifier.set("")
        mergeServiceFiles()
    }

    tasks.withType(GenerateModuleMetadata).configureEach {
        enabled = false
    }

    if (rootProject.publishableModules.contains(project.name)) {
        apply plugin: 'maven-publish'
        apply plugin: 'signing'

        publishing {
}
        def signingKey = (signingKeyFile && file(signingKeyFile).exists()) ? file(signingKeyFile).text : null

        signing {
            required { signingKey != null && signingPassword != null && gradle.taskGraph.allTasks.any { it.name.toLowerCase().contains("sonatype") } }
            if (signingKey && signingPassword) {
                useInMemoryPgpKeys(signingKey, signingPassword)
                sign publishing.publications.named("mavenJava").get()
            }
        }
    }
}
