rootProject.name = 'KashHelper'

include 'kash-helper-common'
include 'kash-helper-config'

include 'kash-helper-paper'
include 'kash-helper-jda'
include 'kash-helper-hytale'

include 'kash-helper-paper:example'
include 'kash-helper-jda:example'
include 'kash-helper-hytale:example'

project(':kash-helper-common').projectDir = file('common')
project(':kash-helper-config').projectDir = file('config')

project(':kash-helper-paper').projectDir = file('platforms/paper')
project(':kash-helper-jda').projectDir = file('platforms/jda')
project(':kash-helper-hytale').projectDir = file('platforms/hytale')

project(':kash-helper-paper:example').projectDir = file('examples/paper')
project(':kash-helper-jda:example').projectDir = file('platforms/jda/example')
project(':kash-helper-hytale:example').projectDir = file('platforms/hytale/example')
