plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":kash-helper-jda")
    compileOnly("net.dv8tion:JDA:6.3.2")

    // Runtime deps needed by KashJdaAddon bootstrap
    runtimeOnly("net.dv8tion:JDA:6.3.2")
    runtimeOnly 'com.fasterxml.jackson.core:jackson-databind:2.20.0'
    runtimeOnly 'ch.qos.logback:logback-classic:1.4.14'
    runtimeOnly('com.zaxxer:HikariCP:5.0.1')
    runtimeOnly 'com.mysql:mysql-connector-j:8.4.0'

}

tasks.register('runExample', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'fr.ibrakash.helper.jda.example.JdaExample'
    workingDir = file('run')
    doFirst { workingDir.mkdirs() }
}
